// The SDD document model. An SDD is a folder, SDDnnn-<slug>/, holding README.md — the title, the
// abstract, the generated index, and every section not moved out yet — plus one file per
// moved-out section, named for its anchor: 3.md, 3.2.md. A section is a heading that carries its
// anchor, `### §3.2 Title`, so a reference like SDD011§3.2 finds its heading wherever it lives.
//
// Everything here is pure: lines in, issues or new lines out. sdd-check.js does the disk and git
// work.

const README = 'README.md';
const ABSTRACT_MAX = 500;

// A section number has no leading zeros, so §3.2 has exactly one spelling.
const NUM = '(?:0|[1-9]\\d*)';
const ANCHOR = `${NUM}(?:\\.${NUM})*`;

const DOC_DIR_RE = /^SDD(\d{3,})-[^\s/\\]+$/;
const FLAT_FILE_RE = /^SDD(\d{3,})-[^\s/\\]+\.md$/;
const SECTION_FILE_RE = new RegExp(`^(${ANCHOR})\\.md$`);
const SECTION_RE = new RegExp(`^§(${ANCHOR})(?:[ \\t]+(.*))?$`);
const TITLE_RE = /^(SDD\d{3,})[ \t]+[—–-][ \t]+(.+)$/;
const FENCE_RE = /^ {0,3}(`{3,}|~{3,})/;
const HEADING_RE = /^ {0,3}(#{1,6})(?:[ \t]+(.*?))?(?:[ \t]+#+)?[ \t]*$/;
const RULE_RE = /^ {0,3}(?:(?:-[ \t]*){3,}|(?:\*[ \t]*){3,}|(?:_[ \t]*){3,})$/;
const LIST_ITEM_RE = /^[ \t]*(?:[-*+]|\d+[.)])[ \t]+/;
const BREADCRUMB_RE = /^> \[SDD\d/;

// A source file, by its extension, and a citation of one of its lines: orders.service.ts:120, or
// a link to blob/main/orders.service.ts#L120.
const CODE_EXT =
  'c|cc|cjs|cpp|cs|css|go|gradle|h|hpp|html|java|js|json|jsx|kt|kts|less|lua|mjs|php|proto|py|rb|rs|sass|scala|scss|sh|sql|svelte|swift|toml|ts|tsx|vue|xml|ya?ml';
const LINE_CITE_RE = new RegExp(`[\\w.-]+\\.(?:${CODE_EXT})(?::\\d+|#L\\d+)`);
const SOURCE_FILE_RE = new RegExp(`\\.(?:${CODE_EXT})$`, 'i');
const isSourceFile = (name) => SOURCE_FILE_RE.test(name);

const INDEX_OPEN = '<!-- sdd:index — generated by sdd-check from the section headings; do not edit -->';
const INDEX_OPEN_RE = /^<!-- sdd:index\b/;
const INDEX_CLOSE = '<!-- /sdd:index -->';

// A label written where a section number belongs: §P6, §A, §03. Lowercase letters alone, §x.y,
// are a placeholder in text about the format, and are left alone.
const TAG = '[A-Za-z0-9](?:[A-Za-z0-9.]*[A-Za-z0-9])?';
const isPlaceholder = (tag) => /^[a-z.]+$/.test(tag);
// What follows a §: a section number, or else a label.
const ITEM = `§(?:(${ANCHOR})(?!\\d)|(${TAG}))`;

// A reference: SDD011, or SDD011§3.2, standing on its own — SDD001_FLAG and a hash like SDD12abc
// are not references. The digits are captured whole, so a non-canonical spelling (SDD11, SDD0011)
// is caught rather than skipped, and so is a label after the §, SDD013§P6.
const REF_RE = new RegExp(`(?<![A-Za-z0-9_])SDD(\\d+)(?:${ITEM}|(?![A-Za-z0-9_]))`, 'g');
const ITEM_AT_RE = new RegExp(`^${ITEM}`);
// Prose: §8.1.2 of SDD006.
const PROSE_RE = new RegExp(`(?<![A-Za-z0-9_§.])§(${ANCHOR})(?!\\d)[ \\t]+(?:of|in)[ \\t]+SDD(\\d+)(?![A-Za-z0-9_])`, 'g');
// A bare §3.2, which inside an SDD's own files means a section of that SDD.
const BARE_RE = new RegExp(`(?<![A-Za-z0-9_§.])${ITEM}`, 'g');
// A § straight after an all-caps name or a number cites another document: RFC 9110 §15.
const EXTERNAL_RE = /(?:^|[^A-Za-z0-9_])(?:[A-Z][A-Z0-9-]*[A-Z0-9]|\d+(?:\.\d+)*)[ \t]+$/;
// Short forms, which borrow the document of the reference before them. What joins a list:
// SDD006§2.4.1/§12, SDD013§4.2 and §5.1, SDD017§6.1–§6.2.
const SEP_RE = /^(?:[ \t]*[,/][ \t]*(?:(?:and|or)[ \t]+)?|[ \t]+(?:and|or)[ \t]+|[ \t]*–[ \t]*|-)/;
// A label after a list item, which the list reads past: SDD005§8.6 (dialog), §8.2. One holding a
// § is not a label: in SDD002, SDD013§2.2 (§4.9) cites SDD002's own §4.9.
const LABEL_RE = /^[ \t]+\([^()§\n]*\)/;
// Parentheses straight after a bare id, whose §s are that doc's: SDD001 (esp. §7, §8).
const PAREN_RE = /^[ \t]*\(([^()\n]*)\)/;
// A markdown link, with or without a title, and the anchor written after it, with or without a
// space: [SDD007](SDD007-seo.md)§4.4.1, [SDD014 — ABAC](SDD014-abac.md) §4,
// [notes](../sdd/SDD002-mail/3.md "Mail").
const LINK_RE = new RegExp(
  `\\[([^\\]\\n]*)\\]\\(([^)\\s]+)(?:[ \\t]+(?:"[^"\\n]*"|'[^'\\n]*'))?\\)(?:[ \\t]*(§${ANCHOR}(?!\\d)))?`,
  'g',
);

// ---------------------------------------------------------------- anchors

const docId = (num) => `SDD${String(num).padStart(3, '0')}`;
const ownFile = (anchor) => `${anchor}.md`;
const depthOf = (anchor) => anchor.split('.').length;
// §3 is `##`, §3.2 is `###`, and so on; markdown stops at six.
const levelFor = (anchor) => Math.min(depthOf(anchor) + 1, 6);
const isWithin = (anchor, of) => anchor.startsWith(`${of}.`);

function parentOf(anchor) {
  const i = anchor.lastIndexOf('.');
  return i < 0 ? null : anchor.slice(0, i);
}

// Numeric, part by part: §3.2 before §3.10, and a parent before its children.
function compareAnchors(a, b) {
  const x = a.split('.').map(Number);
  const y = b.split('.').map(Number);
  for (let i = 0; i < Math.max(x.length, y.length); i++) {
    if (x[i] === undefined) return -1;
    if (y[i] === undefined) return 1;
    if (x[i] !== y[i]) return x[i] - y[i];
  }
  return 0;
}

const byAnchor = (a, b) => compareAnchors(a.anchor, b.anchor);

// ---------------------------------------------------------------- lines

// A file's text as lines, remembering its line ending and whether it ended with one, so an
// edited file keeps both.
function splitLines(text) {
  const eol = text.includes('\r\n') ? '\r\n' : '\n';
  const lines = text.split(/\r?\n/);
  const final = lines.length > 1 && lines[lines.length - 1] === '';
  if (final) lines.pop();
  if (lines.length === 1 && lines[0] === '') lines.pop();
  return { lines, eol, final };
}

function joinLines(lines, eol = '\n', final = true) {
  return lines.join(eol) + (final && lines.length ? eol : '');
}

const isBlank = (line) => !line.trim();

// Drops trailing blank lines and thematic breaks: the separators that sat between two sections.
function trimEnd(lines) {
  const out = [...lines];
  while (out.length && (isBlank(out[out.length - 1]) || RULE_RE.test(out[out.length - 1]))) out.pop();
  return out;
}

const sameLines = (a, b) => a.length === b.length && a.every((line, i) => line === b[i]);

// ---------------------------------------------------------------- scanning

// Headings, fenced lines, code fences and the index block of one file. A heading inside a code
// fence is text.
function scanFile(name, lines) {
  const headings = [];
  const fenced = new Array(lines.length).fill(false);
  const fences = [];
  let fence = null;
  let indexOpen = -1;
  let indexClose = -1;
  lines.forEach((line, i) => {
    const f = FENCE_RE.exec(line);
    if (fence) {
      fenced[i] = true;
      if (f && f[1][0] === fence[0] && f[1].length >= fence.length && line.trim() === f[1]) {
        fence = null;
        fences[fences.length - 1].end = i;
      }
      return;
    }
    if (f) {
      fence = f[1];
      fenced[i] = true;
      fences.push({ i, end: lines.length - 1, info: line.trim().slice(f[1].length).trim() });
      return;
    }
    if (indexOpen < 0 && INDEX_OPEN_RE.test(line)) indexOpen = i;
    else if (indexOpen >= 0 && indexClose < 0 && line.trim() === INDEX_CLOSE) indexClose = i;
    const h = HEADING_RE.exec(line);
    if (!h) return;
    const text = (h[2] || '').trim();
    const heading = { i, level: h[1].length, text };
    if (text.startsWith('§')) {
      const s = SECTION_RE.exec(text);
      if (s) heading.section = { anchor: s[1], title: (s[2] || '').trim() };
      else heading.malformed = true;
    } else if (/^index$/i.test(text)) {
      heading.isIndex = true;
    }
    headings.push(heading);
  });
  const m = SECTION_FILE_RE.exec(name);
  // anchor: null for README.md, the anchor for a section file, undefined for anything else.
  const anchor = name === README ? null : m ? m[1] : undefined;
  return { name, lines, headings, fenced, fences, indexOpen, indexClose, anchor };
}

// The lines of a file that hold its own text: not fenced code, and not what fix generates — the
// index and the breadcrumb.
function textLines(f) {
  const out = [];
  f.lines.forEach((line, i) => {
    if (f.fenced[i] || (i === 0 && f.anchor && BREADCRUMB_RE.test(line))) return;
    if (f.indexOpen >= 0 && i >= f.indexOpen && i <= Math.max(f.indexClose, f.indexOpen)) return;
    out.push({ i, line });
  });
  return out;
}

// Where a section heading's title starts on its line, after its anchor.
const titleStart = (line, anchor) => line.indexOf(`§${anchor}`) + anchor.length + 1;

// README.md first, then section files in anchor order, then anything else.
function orderFiles(files) {
  const rank = (f) => (f.anchor === null ? 0 : f.anchor === undefined ? 2 : 1);
  return [...files.values()].sort(
    (a, b) =>
      rank(a) - rank(b) ||
      (rank(a) === 1 ? compareAnchors(a.anchor, b.anchor) : a.name.localeCompare(b.name)),
  );
}

// files: Map of file name to lines.
function buildModel(files) {
  const scanned = new Map();
  for (const [name, lines] of files) scanned.set(name, scanFile(name, lines));
  const sections = new Map();
  const duplicates = [];
  for (const f of orderFiles(scanned)) {
    for (const h of f.headings) {
      if (!h.section) continue;
      const { anchor, title } = h.section;
      const s = { anchor, title, file: f.name, i: h.i, level: h.level, removed: /^\(removed\b/i.test(title) };
      if (sections.has(anchor)) duplicates.push({ first: sections.get(anchor), again: s });
      else sections.set(anchor, s);
    }
  }
  const readme = scanned.get(README);
  const first = readme && readme.headings[0];
  const h1 = first && first.level === 1 ? first : null;
  return { files: scanned, sections, duplicates, h1 };
}

const hasOwnFile = (s) => s.file === ownFile(s.anchor);
const sortedSections = (m) => [...m.sections.values()].sort(byAnchor);

// The first paragraph under the title.
function abstractOf(readme) {
  const h1 = readme.headings[0];
  if (!h1 || h1.level !== 1) return null;
  const { lines } = readme;
  let i = h1.i + 1;
  while (i < lines.length && isBlank(lines[i])) i++;
  const start = i;
  const body = [];
  for (; i < lines.length && !isBlank(lines[i]) && !HEADING_RE.test(lines[i]) && !RULE_RE.test(lines[i]); i++) {
    body.push(lines[i].trim());
  }
  if (!body.length || /^(>|[-*+][ \t]|\d+[.)][ \t]|\||<!--|```|~~~)/.test(body[0])) return null;
  return { i: start, text: body.join(' ') };
}

// Where a section's text ends in its file: at the next heading outside it, or at the index.
function rangeEnd(f, s) {
  let end = f.lines.length;
  if (f.indexOpen > s.i) end = f.indexOpen;
  for (const h of f.headings) {
    if (h.i <= s.i || h.i >= end) continue;
    if ((h.isIndex && f.name === README) || h.malformed || (h.section && !isWithin(h.section.anchor, s.anchor))) {
      return h.i;
    }
  }
  return end;
}

// ---------------------------------------------------------------- generated lines

const escapeLabel = (s) => s.replace(/[[\]]/g, '\\$&');

// Every section, nested by depth. An entry links the file that holds the section; one with no
// link is in README.md itself.
function renderIndex(m) {
  return sortedSections(m).map((s) => {
    const label = `§${s.anchor} ${s.title}`.trim();
    const entry = s.file === README ? label : `[${escapeLabel(label)}](${s.file})`;
    return `${'  '.repeat(depthOf(s.anchor) - 1)}- ${entry}`;
  });
}

// The first line of a section file: the SDD, then each ancestor section, each linking its file.
// The SDD is named by the README's title when that is well-formed, else by its id alone, so the
// crumb always opens with the id — which is how a crumb is told from text above the heading.
function renderBreadcrumb(m, anchor, id) {
  const title = m.h1 && TITLE_RE.test(m.h1.text) ? m.h1.text : id;
  const chain = [`[${escapeLabel(title)}](${README})`];
  const ancestors = [];
  for (let p = parentOf(anchor); p; p = parentOf(p)) ancestors.unshift(p);
  for (const a of ancestors) {
    const s = m.sections.get(a);
    chain.push(`[${escapeLabel(`§${a} ${s ? s.title : ''}`.trim())}](${ownFile(a)})`);
  }
  return `> ${chain.join(' › ')}`;
}

function currentIndex(readme) {
  if (readme.indexOpen < 0 || readme.indexClose < readme.indexOpen) return null;
  return readme.lines.slice(readme.indexOpen + 1, readme.indexClose);
}

// ---------------------------------------------------------------- checks

// Issues for one SDD folder. `fixable` ones are what fix repairs; a `structural` one stops fix
// from touching the doc at all, because moving text around it could lose or misplace some.
function checkDoc(m, { id, maxLines }) {
  const issues = [];
  const add = (file, i, message, kind = {}) =>
    issues.push({
      file,
      line: i === undefined || i < 0 ? undefined : i + 1,
      level: kind.warning ? 'warning' : 'error',
      message,
      fixable: Boolean(kind.fixable),
      structural: Boolean(kind.structural),
    });

  const readme = m.files.get(README);
  if (!readme) {
    add(README, undefined, 'missing: every SDD folder has a README.md entry file', { structural: true });
  } else {
    const t = m.h1 && TITLE_RE.exec(m.h1.text);
    if (!m.h1) add(README, 0, `must open with the title heading "# ${id} — <title>"`);
    else if (!t) add(README, m.h1.i, `the title heading must read "# ${id} — <title>"`);
    else if (t[1] !== id) add(README, m.h1.i, `the title says ${t[1]}, but the folder is ${id}`);

    const abs = abstractOf(readme);
    if (!abs) {
      add(README, m.h1 ? m.h1.i + 1 : 0, 'no abstract: open with one paragraph, under the title, saying what this SDD covers');
    } else if (abs.text.length > ABSTRACT_MAX) {
      add(README, abs.i, `the abstract is ${abs.text.length} characters; the limit is ${ABSTRACT_MAX}`);
    }

    if (readme.indexOpen >= 0 && readme.indexClose < 0) {
      add(README, readme.indexOpen, `the index has no closing ${INDEX_CLOSE}`, { structural: true });
    } else {
      const cur = currentIndex(readme);
      if (!cur) add(README, undefined, 'no generated index', { fixable: true });
      else if (!sameLines(cur, renderIndex(m))) add(README, readme.indexOpen, 'the index is out of date', { fixable: true });
    }
  }

  for (const f of orderFiles(m.files)) {
    let enclosing = null;
    for (const h of f.headings) {
      if (h.level === 1 && h !== m.h1) add(f.name, h.i, 'only README.md opens with a level-1 heading, and only once');
      if (h.malformed) {
        add(f.name, h.i, `malformed section heading "${h.text}": write "§<number> <title>", like "§3.2 Retries"`, {
          structural: true,
        });
      } else if (h.section) {
        const { anchor, title } = h.section;
        enclosing = anchor;
        if (!title) add(f.name, h.i, `§${anchor} has no title`);
        const want = levelFor(anchor);
        if (h.level !== want) {
          add(f.name, h.i, `§${anchor} is a level-${h.level} heading; its depth takes ${'#'.repeat(want)}`, { fixable: true });
        }
      } else if (h.isIndex && f.name === README) {
        enclosing = null;
      } else if (enclosing && h.level > 1 && h.level <= levelFor(enclosing)) {
        add(
          f.name,
          h.i,
          `the heading "${h.text}" sits at section level inside §${enclosing}: number it, or make it deeper than ${'#'.repeat(levelFor(enclosing))}`,
          { structural: true },
        );
      }
    }
  }

  for (const { first, again } of m.duplicates) {
    add(again.file, again.i, `§${again.anchor} is defined twice; the other is ${first.file}:${first.i + 1}`, { structural: true });
  }

  for (const s of sortedSections(m)) {
    const p = parentOf(s.anchor);
    const parent = p && m.sections.get(p);
    if (p && !parent) {
      add(s.file, s.i, `§${s.anchor} has no parent: there is no §${p}`, { structural: true });
    } else if (hasOwnFile(s)) {
      if (parent && !hasOwnFile(parent)) {
        add(s.file, s.i, `§${s.anchor} has its own file, but its parent §${p} does not; put §${s.anchor} back into ${parent.file}`, {
          structural: true,
        });
      }
    } else {
      const home = parent ? parent.file : README;
      if (s.file !== home) add(s.file, s.i, `§${s.anchor} belongs in ${home}, with its parent`, { structural: true });
    }
  }

  // A section file opens with its breadcrumb, then its own heading. Nothing else goes above.
  for (const f of orderFiles(m.files)) {
    if (f.anchor === null) continue;
    if (f.anchor === undefined) {
      add(f.name, undefined, 'not a section file: a file here is README.md or is named for the section it holds, like 3.2.md');
      continue;
    }
    const first = f.headings.find((h) => h.section || h.malformed);
    if (!first || !first.section || first.section.anchor !== f.anchor) {
      add(f.name, first ? first.i : undefined, `must open with the heading of §${f.anchor}`, { structural: true });
      continue;
    }
    for (let i = 0; i < first.i; i++) {
      if (isBlank(f.lines[i]) || (i === 0 && BREADCRUMB_RE.test(f.lines[i]))) continue;
      add(f.name, i, `text above the §${f.anchor} heading; only the breadcrumb goes there`, { structural: true });
      break;
    }
    const crumb = renderBreadcrumb(m, f.anchor, id);
    if (f.lines[0] !== crumb) {
      add(f.name, 0, BREADCRUMB_RE.test(f.lines[0] || '') ? 'the breadcrumb is out of date' : 'no breadcrumb', { fixable: true });
    }
  }

  // Siblings move out together: once one has its own file, all of them do.
  for (const kids of siblingGroups(m).values()) {
    const moved = kids.find(hasOwnFile);
    if (!moved) continue;
    for (const s of kids) {
      if (!hasOwnFile(s)) add(s.file, s.i, `§${s.anchor} needs its own file, like its sibling §${moved.anchor}`, { fixable: true });
    }
  }

  for (const f of orderFiles(m.files)) {
    for (const { i, line } of textLines(f)) {
      const c = LINE_CITE_RE.exec(line);
      if (c) add(f.name, i, `cites a line number, ${c[0]}: lines move with every change, so cite the symbol`);
    }
  }

  for (const f of orderFiles(m.files)) {
    if (f.lines.length <= maxLines || f.anchor === undefined) continue;
    const owner = f.anchor;
    const inline = inlineChildren(m, f.name, owner);
    const what = `${f.lines.length} lines, over the ${maxLines}-line limit`;
    if (inline.length) {
      add(f.name, undefined, `${what}; fix moves its ${inline.length} ${owner ? 'subsections' : 'sections'} into their own files`, {
        fixable: true,
      });
    } else if (owner) {
      add(f.name, undefined, `${what}, and §${owner} has no subsections to move out: divide it into nested sections (§${owner}.1, §${owner}.2, …), then run fix`);
    } else {
      add(f.name, undefined, `${what}, and has no sections left to move out: shorten the text above the index`);
    }
  }

  return issues;
}

function siblingGroups(m) {
  const groups = new Map();
  for (const s of sortedSections(m)) {
    const p = parentOf(s.anchor) ?? '';
    if (!groups.has(p)) groups.set(p, []);
    groups.get(p).push(s);
  }
  return groups;
}

// The direct subsections still inside a file. owner is null for README.md, whose children are
// the top-level sections.
function inlineChildren(m, fileName, owner) {
  return sortedSections(m).filter((s) => s.file === fileName && s.anchor !== owner && parentOf(s.anchor) === owner);
}

// ---------------------------------------------------------------- fix

// The next section to move into its own file: a sibling of one already moved, or else the first
// subsection of a file over the limit — whose siblings then follow by the first rule.
function nextMove(m, maxLines) {
  for (const kids of siblingGroups(m).values()) {
    if (!kids.some(hasOwnFile)) continue;
    const s = kids.find((k) => !hasOwnFile(k));
    if (s) return s.anchor;
  }
  for (const f of orderFiles(m.files)) {
    if (f.lines.length <= maxLines || f.anchor === undefined) continue;
    const [kid] = inlineChildren(m, f.name, f.anchor);
    if (kid) return kid.anchor;
  }
  return null;
}

// Cuts one section, with its subsections, out of its file into <anchor>.md.
function moveOut(files, m, anchor, id) {
  const s = m.sections.get(anchor);
  const f = m.files.get(s.file);
  const name = ownFile(anchor);
  if (files.has(name)) throw new Error(`${name} already exists`);
  const end = rangeEnd(f, s);
  const lines = files.get(s.file);
  files.set(s.file, trimEnd([...lines.slice(0, s.i), ...lines.slice(end)]));
  files.set(name, [renderBreadcrumb(m, anchor, id), '', ...trimEnd(lines.slice(s.i, end))]);
}

function applyBreadcrumbs(files, m, id) {
  for (const f of m.files.values()) {
    if (!f.anchor) continue;
    const crumb = renderBreadcrumb(m, f.anchor, id);
    const lines = files.get(f.name);
    if (lines[0] === crumb) continue;
    if (BREADCRUMB_RE.test(lines[0] || '')) lines[0] = crumb;
    else if (lines[0] === '') lines.unshift(crumb);
    else lines.unshift(crumb, '');
  }
}

function applyIndex(files, m) {
  const r = m.files.get(README);
  const lines = files.get(README);
  const block = [INDEX_OPEN, ...renderIndex(m), INDEX_CLOSE];
  if (r.indexOpen >= 0) {
    files.set(README, [...lines.slice(0, r.indexOpen), ...block, ...lines.slice(r.indexClose + 1)]);
    return;
  }
  const heading = r.headings.find((h) => h.isIndex);
  if (heading) {
    // An index written by hand: its list items give way to the generated block. Anything else
    // under the heading — a thematic break that closed it, a paragraph — is text, and follows the
    // block, one blank line between paragraphs.
    const after = r.headings.find((h) => h.i > heading.i);
    const end = after ? after.i : lines.length;
    const rest = [];
    for (let i = heading.i + 1; i < end; i++) {
      const line = lines[i];
      if (!r.fenced[i] && LIST_ITEM_RE.test(line)) continue;
      if (!r.fenced[i] && isBlank(line) && (!rest.length || isBlank(rest[rest.length - 1]))) continue;
      rest.push(line);
    }
    while (rest.length && isBlank(rest[rest.length - 1])) rest.pop();
    const body = ['', ...block];
    if (rest.length) body.push('', ...rest);
    if (end < lines.length) body.push('');
    files.set(README, [...lines.slice(0, heading.i + 1), ...body, ...lines.slice(end)]);
    return;
  }
  const first = r.headings.find((h) => h.section);
  if (first) files.set(README, [...lines.slice(0, first.i), '## Index', '', ...block, '', ...lines.slice(first.i)]);
  else files.set(README, [...trimEnd(lines), '', '## Index', '', ...block]);
}

// Everything fix repairs, in one pass: heading levels, then moves, with the breadcrumbs and the
// index regenerated before every size check, since both count towards a file's lines.
// Returns the new files and what changed, or the structural issues that stopped it.
function fixDoc(input, ctx) {
  const files = new Map([...input].map(([name, lines]) => [name, [...lines]]));
  let m = buildModel(files);
  const blocked = checkDoc(m, ctx).filter((x) => x.structural);
  if (blocked.length) return { files: input, actions: [], blocked };

  const actions = [];
  let levels = 0;
  for (const f of m.files.values()) {
    for (const h of f.headings) {
      if (!h.section || h.level === levelFor(h.section.anchor)) continue;
      files.get(f.name)[h.i] = `${'#'.repeat(levelFor(h.section.anchor))} ${h.text}`;
      levels++;
    }
  }
  if (levels) actions.push(`set ${levels} heading level${levels === 1 ? '' : 's'} from section depth`);

  const moves = new Map();
  for (;;) {
    m = buildModel(files);
    applyBreadcrumbs(files, m, ctx.id);
    applyIndex(files, buildModel(files));
    m = buildModel(files);
    const next = nextMove(m, ctx.maxLines);
    if (!next) break;
    const from = m.sections.get(next).file;
    if (!moves.has(from)) moves.set(from, []);
    moves.get(from).push(next);
    moveOut(files, m, next, ctx.id);
  }
  for (const [from, anchors] of moves) {
    actions.push(`moved ${anchors.map((a) => `§${a}`).join(', ')} out of ${from} into their own files`);
  }

  const crumbs = [...input.keys()].filter(
    (name) => SECTION_FILE_RE.test(name) && files.has(name) && files.get(name)[0] !== input.get(name)[0],
  ).length;
  if (crumbs) actions.push(`updated ${crumbs} breadcrumb${crumbs === 1 ? '' : 's'}`);
  const before = input.has(README) ? currentIndex(scanFile(README, input.get(README))) : null;
  const after = currentIndex(m.files.get(README));
  if (!before || !sameLines(before, after)) actions.push('regenerated the index');

  return { files, actions, blocked: null };
}

// ---------------------------------------------------------------- lint

// Leads for a content pass, never errors: each is likely, not certain, to break a Content rule
// of the skill, and the agent reading it decides. English wording only.

// Text that tells history instead of the current state.
const HISTORY_RE = new RegExp(
  [
    '(?<!\\b(?:is|are|was|were|be|been|being|get|gets|got) )\\bused to\\b',
    '\\b(?:previously|formerly|originally|initially|anymore|newly)\\b',
    '\\bno longer\\b(?! than)',
    '\\b(?:was|were|has been|have been|had been) (?:added|changed|deleted|dropped|extended|fixed|introduced|merged|migrated|moved|removed|renamed|replaced|reworked|rewritten|split|switched)\\b',
    '\\b(?:we|they) (?:added|changed|decided|dropped|introduced|moved|removed|renamed|replaced|switched)\\b',
    '(?<!\\b(?:is|are|be|been|being|get|gets|got) )\\breplaced (?:a|an|the)\\b',
    '(?<!\\b(?:is|are|be|been|being|get|gets|got) )\\bbriefly (?:had|was|were|\\w+ed)\\b',
    '\\b(?:was|were|had) briefly\\b',
    '\\b(?:is|are) now\\b',
    '\\bnow (?:also|instead)\\b',
    '\\b(?:has|have) since\\b',
    '\\buntil (?:recently|now)\\b',
    '\\b(?:became|landed)\\b',
    '\\bchanged from\\b',
    '\\bin the past\\b',
    '\\bsince (?:SDD\\d+|v?\\d+\\.\\d+|then\\b|the (?:change|migration|refactor|rewrite)\\b)',
    '\\b(?:before|after) (?:this|the) (?:change|migration|PR|refactor|rewrite)\\b',
    '\\bwhat changed\\b',
    '\\bthe old (?:approach|behaviou?r|code|design|flow|format|implementation|list|name|scheme|version)\\b',
    '^(?:[>*_ \\t]|\\*\\*)*updated?:',
  ].join('|'),
  'i',
);

// Fences that hold a picture or plain text rather than code.
const NON_CODE_FENCES = new Set(['', 'text', 'txt', 'plain', 'plaintext', 'ascii', 'mermaid', 'plantuml', 'puml', 'dot', 'graphviz', 'svgbob', 'math', 'latex', 'tex', 'md', 'markdown', 'console']);

const INLINE_CODE_RE = /`([^`\n]+)`/g;
const FILE_NAME_RE = new RegExp(`^[\\w.-]+\\.(?:${CODE_EXT})$`);
const HOST_RE = /^[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)+$/;

// A line with its code spans and link targets blanked, so their text is not read as wording.
const wording = (line) => line.replace(INLINE_CODE_RE, (s) => ' '.repeat(s.length)).replace(/\]\([^)\s]*\)/g, ']()');

// History wording and code fences, for one SDD: { file, i, message }.
function lintDoc(m) {
  const out = [];
  for (const f of orderFiles(m.files)) {
    for (const fence of f.fences) {
      const lang = fence.info.split(/[\s{,]/)[0].toLowerCase();
      if (NON_CODE_FENCES.has(lang)) continue;
      const n = Math.max(0, fence.end - fence.i - 1);
      out.push({ file: f.name, i: fence.i, message: `a ${n}-line \`\`\`${lang} block: copied code goes stale; state the rule it shows and cite the symbol` });
    }
    for (const h of f.headings) {
      if (!h.section) continue;
      const title = f.lines[h.i].slice(titleStart(f.lines[h.i], h.section.anchor));
      for (const r of findRefs(title, { bare: true })) {
        if (r.kind === 'bare' && r.tag) {
          out.push({ file: f.name, i: h.i, message: `the title carries a label, "§${r.tag}": drop it once no reference cites the label` });
        }
      }
    }
    for (const { i, line } of textLines(f)) {
      const h = HISTORY_RE.exec(wording(line));
      if (h) out.push({ file: f.name, i, message: `reads as history, "${h[0].trim()}": state what is true now` });
    }
  }
  return out.sort((a, b) => a.file.localeCompare(b.file) || a.i - b.i);
}

// A name in backticks the code should still have, and how to look for it: a path or a file name
// in the repository's file list, an identifier by its last part in the code's text. Only what has
// the shape of code is looked for — a path with an extension, a dotted member, a call, camelCase,
// snake_case. A plain word in backticks is as likely a value or a term.
function codeName(raw) {
  const t = raw.trim().replace(/^@/, '').replace(/^new[ \t]+/, '').replace(/\([^()]*\)$/, '()');
  if (!t || /\s|[*{}<>$=|\\]|:\/\/|x{3}/i.test(t)) return null;
  if (t.includes('/')) {
    // apps/web/.../cart.ts elides directories: what follows the ellipsis is a path from somewhere.
    const segs = t.split('/');
    const cut = Math.max(segs.lastIndexOf('...'), segs.lastIndexOf('…'));
    const parts = segs.slice(cut + 1).filter((p) => p && p !== '.' && p !== '..');
    // A route, /orders/:id, or a URL, api.example.com/v1, is not a file.
    if (!parts.length || t.startsWith('/') || t.includes(':') || (parts.length > 1 && HOST_RE.test(parts[0]))) return null;
    const probe = parts.join('/');
    if (t.endsWith('/')) return { kind: 'dir', probe };
    // a/b without an extension is as often "this or that" as a path.
    return /\.[A-Za-z0-9]+$/.test(probe) ? { kind: 'path', probe } : null;
  }
  if (FILE_NAME_RE.test(t)) return { kind: 'file', probe: t };
  const id = /^([A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*)(\(\))?$/.exec(t);
  if (!id) return null;
  const parts = id[1].split('.');
  const last = parts[parts.length - 1];
  // VARCHAR(500), NOW(): SQL, not a name the code defines.
  if (last.length < 4 || /^_|_$/.test(last) || (id[2] && !/[a-z]/.test(id[1]))) return null;
  const shaped = parts.length > 1 || Boolean(id[2]) || /[a-z][A-Z]|[A-Za-z0-9]_[A-Za-z0-9]/.test(last);
  return shaped ? { kind: 'name', probe: last } : null;
}

// Every name in backticks in one SDD's text that codeName would look for: { file, i, token, kind, probe }.
function codeNames(m) {
  const out = [];
  for (const f of orderFiles(m.files)) {
    for (const { i, line } of textLines(f)) {
      for (const c of line.matchAll(INLINE_CODE_RE)) {
        const n = codeName(c[1]);
        if (n) out.push({ file: f.name, i, token: c[1].trim(), ...n });
      }
    }
  }
  return out;
}

// ---------------------------------------------------------------- references

// A link target's path segments, without its fragment or query.
const targetParts = (target) => target.split('#')[0].split('?')[0].split('/');

// The SDD a link target points into — a file (SDD006-order-workflow.md), or a folder, whether
// the link ends on it (../sdd/SDD006-order-workflow) or goes into it (SDD006-order-workflow/3.md):
// its number, or null.
function linkedDoc(target) {
  const m = targetParts(target)
    .map((p) => FLAT_FILE_RE.exec(p) || DOC_DIR_RE.exec(p))
    .find(Boolean);
  return m ? Number(m[1]) : null;
}

// The § item starting at `at` — a section number or a label — or null, for none or a placeholder.
function itemAt(line, at) {
  const m = ITEM_AT_RE.exec(line.slice(at));
  if (!m || (m[2] && isPlaceholder(m[2]))) return null;
  return { col: at, anchor: m[1] || null, tag: m[2] || null, text: m[0], end: at + m[0].length };
}

const isExternal = (line, col) => EXTERNAL_RE.test(line.slice(0, col));

// The § items inside parentheses, from `from` to `to`, each with what joins it to the one before
// when that is a slash, so the full form can write a comma there instead.
function itemsWithin(line, from, to, taken) {
  const out = [];
  let prev = null;
  for (const m of line.slice(from, to).matchAll(BARE_RE)) {
    const it = itemAt(line, from + m.index);
    if (!it || taken.has(it.col) || isExternal(line, it.col)) continue;
    const between = prev === null ? null : line.slice(prev, it.col);
    const slash = between !== null && SEP_RE.exec(between)?.[0] === between && between.includes('/');
    out.push({ ...it, prefix: true, join: slash ? { from: prev, to: it.col, text: ', ' } : null });
    prev = it.end;
  }
  return out;
}

// The sections a reference lends its document to, read from `p`, just after it: the rest of a
// list, SDD006§2.4.1/§12; parentheses after a bare id, SDD001 (esp. §7, §8); a § after a space,
// SDD007 §8. Each carries the edits that write it in the full form: `prefix` puts the id before
// its §, and `join` replaces the text that joined it to the reference before.
function shortForms(line, p, anchored, taken) {
  const out = [];
  const rest = () => line.slice(p);
  if (!anchored) {
    const space = /^[ \t]+(?=§)/.exec(rest());
    const it = space && itemAt(line, p + space[0].length);
    if (!it || taken.has(it.col)) {
      const paren = PAREN_RE.exec(rest());
      if (paren) out.push(...itemsWithin(line, p + paren[0].indexOf('(') + 1, p + paren[0].length - 1, taken));
      return out;
    }
    out.push({ ...it, prefix: false, join: { from: p, to: it.col, text: '' } });
    p = it.end;
  }
  for (;;) {
    const label = LABEL_RE.exec(rest());
    if (label) p += label[0].length;
    const sep = SEP_RE.exec(rest());
    const it = sep && itemAt(line, p + sep[0].length);
    if (!it || taken.has(it.col)) break;
    out.push({ ...it, prefix: true, join: sep[0].includes('/') ? { from: p, to: it.col, text: ', ' } : null });
    p = it.end;
  }
  return out;
}

// The SDD references on one line. kind: full (SDD011§3.2 or SDD011), noncanonical (SDD11),
// short (a § borrowing the document of the reference before it — see shortForms), prose (§8.1.2
// of SDD006), link (a markdown link to an SDD file, looked for only when `markdown`), or bare
// (§3.2 alone, looked for only when `bare`). A full, short or bare ref with a label where its
// number belongs, SDD013§P6, has `tag` set and no anchor.
function findRefs(line, { bare = false, markdown = false } = {}) {
  const refs = [];
  const taken = new Set();
  const spans = [];
  if (markdown) {
    for (const m of line.matchAll(LINK_RE)) {
      const num = linkedDoc(m[2]);
      if (num === null) continue;
      const anchor = m[3] ? m[3].slice(1) : null;
      refs.push({ col: m.index, kind: 'link', num, anchor, text: m[0] });
      spans.push([m.index, m.index + m[0].length]);
      if (anchor) taken.add(m.index + m[0].length - m[3].length);
    }
  }
  for (const m of line.matchAll(PROSE_RE)) {
    refs.push({ col: m.index, kind: 'prose', num: Number(m[2]), digits: m[2], anchor: m[1], text: m[0] });
    taken.add(m.index);
  }
  for (const m of line.matchAll(REF_RE)) {
    if (spans.some(([a, b]) => m.index >= a && m.index < b)) continue;
    if (refs.some((r) => r.kind === 'prose' && m.index > r.col && m.index < r.col + r.text.length)) continue;
    const digits = m[1];
    const num = Number(digits);
    const id = `SDD${digits}`;
    const tag = m[3] && !isPlaceholder(m[3]) ? m[3] : null;
    const kind = docId(num) === id ? 'full' : 'noncanonical';
    const text = m[3] && !tag ? id : m[0];
    refs.push({ col: m.index, kind, num, anchor: m[2] || null, tag, text });
    if (m[2] || m[3]) taken.add(m.index + id.length);
    for (const s of shortForms(line, m.index + text.length, Boolean(m[2] || tag), taken)) {
      taken.add(s.col);
      refs.push({ ...s, kind: 'short', num, id, head: text });
    }
  }
  if (bare) {
    for (const m of line.matchAll(BARE_RE)) {
      if (taken.has(m.index) || isExternal(line, m.index)) continue;
      const it = itemAt(line, m.index);
      if (it) refs.push({ col: it.col, kind: 'bare', num: null, anchor: it.anchor, tag: it.tag, text: it.text });
    }
  }
  return refs.sort((a, b) => a.col - b.col);
}

// Every reference in a file, with its line index. In markdown, fenced code is skipped; in an
// SDD's own files, so are the lines that define anchors rather than cite them — the index, the
// breadcrumb, a section heading's anchor — and a bare §3.2 counts as a reference to that SDD. A
// section's title is read for what it cites, (removed; see §3.6) or (SDD013§P6), but a bare label
// in it is where that label is defined, not a citation: lint reports those.
function refsInFile(name, lines, { markdown, inDoc }) {
  const scan = markdown ? scanFile(name, lines) : null;
  const skip = new Set();
  const titles = new Map();
  if (scan) {
    scan.fenced.forEach((f, i) => f && skip.add(i));
    if (inDoc) {
      for (const h of scan.headings) {
        if (h.malformed) skip.add(h.i);
        else if (h.section) titles.set(h.i, titleStart(lines[h.i], h.section.anchor));
      }
      if (scan.indexOpen >= 0) for (let i = scan.indexOpen; i <= Math.max(scan.indexClose, scan.indexOpen); i++) skip.add(i);
      if (BREADCRUMB_RE.test(lines[0] || '')) skip.add(0);
    }
  }
  const out = [];
  lines.forEach((line, i) => {
    if (skip.has(i) || (!line.includes('SDD') && !(inDoc && line.includes('§')))) return;
    const from = titles.get(i) || 0;
    for (const ref of findRefs(line.slice(from), { bare: Boolean(inDoc), markdown })) {
      if (from && ref.kind === 'bare' && ref.tag) continue;
      out.push({ i, ...ref, col: ref.col + from });
    }
  });
  return out;
}

// What is wrong with one reference, if anything. docsByNum maps a number to its SDDs (more than
// one is a numbering clash, reported elsewhere); ownDoc is the SDD whose file holds the reference.
function validateRef(ref, docsByNum, ownDoc) {
  const err = (message) => ({ level: 'error', message });
  if (ref.kind === 'noncanonical') return err(`write ${docId(ref.num)}, not ${ref.text.replace(/§.*/, '')}`);
  const doc = ref.kind === 'bare' ? ownDoc : (docsByNum.get(ref.num) || [])[0];
  const id = ref.kind === 'bare' ? ownDoc.id : docId(ref.num);
  if (ref.tag) return err(doc ? tagMessage(id, ref.tag, doc.model, docsByNum) : `${id} does not exist`);
  const full = `${id}${ref.anchor ? `§${ref.anchor}` : ''}`;
  if (ref.kind === 'short') return err(`short form: write ${full}, not §${ref.anchor} after ${ref.head}`);
  if (ref.kind === 'prose') return err(`write ${full}, not "${ref.text}"`);
  if (ref.kind === 'link') return err(`a link by file path breaks when the file moves: write ${full}`);
  if (!doc) return err(`${id} does not exist`);
  if (!ref.anchor) return null;
  const s = doc.model.sections.get(ref.anchor);
  if (!s) return err(ref.kind === 'bare' ? `no §${ref.anchor} in ${id}` : `${id} has no §${ref.anchor}`);
  if (s.removed) return { level: 'warning', message: `${id}§${ref.anchor} was removed: ${s.title}` };
  return null;
}

// The sections of one doc whose titles carry a label bare, (§P6). A title carrying SDD013§P6
// cites SDD013's label, and is not where this doc's label is defined.
function carriersOf(model, tag) {
  const re = new RegExp(`(?<![A-Za-z0-9_§.])§${tag.replace(/\./g, '\\.')}(?![A-Za-z0-9])`);
  return sortedSections(model)
    .filter((s) => re.test(s.title))
    .map((s) => `§${s.anchor}`);
}

// A label cited where a number belongs. The sections whose titles carry the label are where it
// likely points, so the message names them — while the headings still carry the labels. When the
// doc it is cited in has none, the docs that do are named instead: a bare label is often another
// doc's. They are candidates, not an answer.
function tagMessage(id, tag, model, docsByNum) {
  const what = `"§${tag}" is not a section number`;
  const own = carriersOf(model, tag);
  if (own.length === 1) return `${what}; the one heading in ${id} that carries it is ${own[0]}`;
  if (own.length) return `${what}; the headings in ${id} that carry it: ${own.join(', ')}`;
  const elsewhere = [...docsByNum.keys()]
    .sort((a, b) => a - b)
    .map((num) => docsByNum.get(num)[0])
    .filter((d) => d.id !== id)
    .map((d) => [d.id, carriersOf(d.model, tag)])
    .filter(([, found]) => found.length)
    .map(([other, found]) => `${other} (${found.join(', ')})`);
  if (elsewhere.length) return `${what}; no heading in ${id} carries it, but these do: ${elsewhere.join('; ')}`;
  return `${what}, and no heading in ${id} carries it`;
}

// Migration: every reference in the full form. SDD006§2.4.1/§12 becomes SDD006§2.4.1, SDD006§12;
// SDD007 §8 becomes SDD007§8; SDD001 (esp. §7) becomes SDD001 (esp. SDD001§7); and "§8.1.2 of
// SDD006" becomes SDD006§8.1.2.
function expandRefs(line) {
  const edits = [];
  let count = 0;
  for (const r of findRefs(line)) {
    if (r.kind === 'prose') {
      edits.push([r.col, r.col + r.text.length, `SDD${r.digits}§${r.anchor}`]);
    } else if (r.kind === 'short') {
      if (r.prefix) edits.push([r.col, r.col, r.id]);
      if (r.join) edits.push([r.join.from, r.join.to, r.join.text]);
    } else {
      continue;
    }
    count++;
  }
  let out = line;
  for (const [from, to, text] of edits.sort((a, b) => b[0] - a[0] || b[1] - a[1])) {
    out = out.slice(0, from) + text + out.slice(to);
  }
  return { line: out, count };
}

// Migration: a markdown link to a single-file SDD becomes its plain id, since the file moves and
// an id never does. [SDD006](SDD006-order-workflow.md)§3.1 becomes SDD006§3.1, and
// [order workflow](SDD006-order-workflow.md) becomes "order workflow (SDD006)".
function rewriteDocLinks(line, idForFile) {
  let count = 0;
  const out = line.replace(LINK_RE, (whole, text, target, anchor = '') => {
    const id = idForFile(targetParts(target).pop());
    if (!id) return whole;
    count++;
    const label = text.trim();
    if (!label || label === id) return `${id}${anchor}`;
    if (!anchor && label.includes(id)) return label;
    return `${label} (${id}${anchor})`;
  });
  return { line: out, count };
}

module.exports = {
  README,
  ABSTRACT_MAX,
  DOC_DIR_RE,
  FLAT_FILE_RE,
  INDEX_OPEN,
  INDEX_CLOSE,
  docId,
  isSourceFile,
  parentOf,
  compareAnchors,
  levelFor,
  splitLines,
  joinLines,
  scanFile,
  buildModel,
  abstractOf,
  renderIndex,
  renderBreadcrumb,
  checkDoc,
  fixDoc,
  lintDoc,
  codeName,
  codeNames,
  findRefs,
  refsInFile,
  validateRef,
  expandRefs,
  rewriteDocLinks,
};
