// The SDD document model. An SDD is a folder, SDDnnn-<slug>/, holding README.md — the title, the
// abstract, the generated index, and every section not moved out yet — plus one file per
// moved-out section, named for its anchor: 3.md, 3.2.md. A section is a heading that carries its
// anchor, `### §3.2 Title`, so a reference like SDD011§3.2 finds its heading wherever it lives.
//
// Everything here is pure: lines in, issues or new lines out. sdd-check.js does the disk and git
// work.

const README = 'README.md';
const ABSTRACT_MAX = 500;

// A section number has no leading zeros, so §3.2 has exactly one spelling.
const NUM = '(?:0|[1-9]\\d*)';
const ANCHOR = `${NUM}(?:\\.${NUM})*`;

const DOC_DIR_RE = /^SDD(\d{3,})-[^\s/\\]+$/;
const FLAT_FILE_RE = /^SDD(\d{3,})-[^\s/\\]+\.md$/;
const SECTION_FILE_RE = new RegExp(`^(${ANCHOR})\\.md$`);
const SECTION_RE = new RegExp(`^§(${ANCHOR})(?:[ \\t]+(.*))?$`);
const TITLE_RE = /^(SDD\d{3,})[ \t]+[—–-][ \t]+(.+)$/;
const FENCE_RE = /^ {0,3}(`{3,}|~{3,})/;
const HEADING_RE = /^ {0,3}(#{1,6})(?:[ \t]+(.*?))?(?:[ \t]+#+)?[ \t]*$/;
const RULE_RE = /^ {0,3}(?:(?:-[ \t]*){3,}|(?:\*[ \t]*){3,}|(?:_[ \t]*){3,})$/;
const LIST_ITEM_RE = /^[ \t]*(?:[-*+]|\d+[.)])[ \t]+/;
const BREADCRUMB_RE = /^> \[SDD\d/;

const INDEX_OPEN = '<!-- sdd:index — generated by sdd-check from the section headings; do not edit -->';
const INDEX_OPEN_RE = /^<!-- sdd:index\b/;
const INDEX_CLOSE = '<!-- /sdd:index -->';

// A reference: SDD011, or SDD011§3.2, standing on its own — SDD001_FLAG and a hash like SDD12abc
// are not references. The digits are captured whole, so a non-canonical spelling (SDD11, SDD0011)
// is caught rather than skipped.
const REF_RE = new RegExp(`(?<![A-Za-z0-9_])SDD(\\d+)(?:§(${ANCHOR})(?!\\d)|(?![A-Za-z0-9_]))`, 'g');
// A short form: the §12 in SDD006§2.4.1/§12, borrowing the document of the reference before it.
const TAIL_RE = new RegExp(`^([ \\t]*[,/][ \\t]*)§(${ANCHOR})(?!\\d)`);
const SHORT_FORM_RE = new RegExp(
  `(?<![A-Za-z0-9_])(SDD\\d+)§(${ANCHOR})(?!\\d)((?:[ \\t]*[,/][ \\t]*§${ANCHOR}(?!\\d))+)`,
  'g',
);
const TAIL_ANCHOR_RE = new RegExp(`§(${ANCHOR})(?!\\d)`, 'g');
// Prose: §8.1.2 of SDD006.
const PROSE_RE = new RegExp(`(?<![A-Za-z0-9_§.])§(${ANCHOR})(?!\\d)[ \\t]+(?:of|in)[ \\t]+SDD(\\d+)(?![A-Za-z0-9_])`, 'g');
// A bare §3.2, which inside an SDD's own files means a section of that SDD.
const BARE_RE = new RegExp(`(?<![A-Za-z0-9_§.])§(${ANCHOR})(?!\\d)`, 'g');
// A markdown link, with or without a title, and the anchor written straight after it:
// [SDD007](SDD007-seo.md)§4.4.1, [notes](../sdd/SDD002-mail/3.md "Mail").
const LINK_RE = new RegExp(
  `\\[([^\\]\\n]*)\\]\\(([^)\\s]+)(?:[ \\t]+(?:"[^"\\n]*"|'[^'\\n]*'))?\\)(§${ANCHOR}(?!\\d))?`,
  'g',
);

// ---------------------------------------------------------------- anchors

const docId = (num) => `SDD${String(num).padStart(3, '0')}`;
const ownFile = (anchor) => `${anchor}.md`;
const depthOf = (anchor) => anchor.split('.').length;
// §3 is `##`, §3.2 is `###`, and so on; markdown stops at six.
const levelFor = (anchor) => Math.min(depthOf(anchor) + 1, 6);
const isWithin = (anchor, of) => anchor.startsWith(`${of}.`);

function parentOf(anchor) {
  const i = anchor.lastIndexOf('.');
  return i < 0 ? null : anchor.slice(0, i);
}

// Numeric, part by part: §3.2 before §3.10, and a parent before its children.
function compareAnchors(a, b) {
  const x = a.split('.').map(Number);
  const y = b.split('.').map(Number);
  for (let i = 0; i < Math.max(x.length, y.length); i++) {
    if (x[i] === undefined) return -1;
    if (y[i] === undefined) return 1;
    if (x[i] !== y[i]) return x[i] - y[i];
  }
  return 0;
}

const byAnchor = (a, b) => compareAnchors(a.anchor, b.anchor);

// ---------------------------------------------------------------- lines

// A file's text as lines, remembering its line ending and whether it ended with one, so an
// edited file keeps both.
function splitLines(text) {
  const eol = text.includes('\r\n') ? '\r\n' : '\n';
  const lines = text.split(/\r?\n/);
  const final = lines.length > 1 && lines[lines.length - 1] === '';
  if (final) lines.pop();
  if (lines.length === 1 && lines[0] === '') lines.pop();
  return { lines, eol, final };
}

function joinLines(lines, eol = '\n', final = true) {
  return lines.join(eol) + (final && lines.length ? eol : '');
}

const isBlank = (line) => !line.trim();

// Drops trailing blank lines and thematic breaks: the separators that sat between two sections.
function trimEnd(lines) {
  const out = [...lines];
  while (out.length && (isBlank(out[out.length - 1]) || RULE_RE.test(out[out.length - 1]))) out.pop();
  return out;
}

const sameLines = (a, b) => a.length === b.length && a.every((line, i) => line === b[i]);

// ---------------------------------------------------------------- scanning

// Headings, fenced lines and the index block of one file. A heading inside a code fence is text.
function scanFile(name, lines) {
  const headings = [];
  const fenced = new Array(lines.length).fill(false);
  let fence = null;
  let indexOpen = -1;
  let indexClose = -1;
  lines.forEach((line, i) => {
    const f = FENCE_RE.exec(line);
    if (fence) {
      fenced[i] = true;
      if (f && f[1][0] === fence[0] && f[1].length >= fence.length && line.trim() === f[1]) fence = null;
      return;
    }
    if (f) {
      fence = f[1];
      fenced[i] = true;
      return;
    }
    if (indexOpen < 0 && INDEX_OPEN_RE.test(line)) indexOpen = i;
    else if (indexOpen >= 0 && indexClose < 0 && line.trim() === INDEX_CLOSE) indexClose = i;
    const h = HEADING_RE.exec(line);
    if (!h) return;
    const text = (h[2] || '').trim();
    const heading = { i, level: h[1].length, text };
    if (text.startsWith('§')) {
      const s = SECTION_RE.exec(text);
      if (s) heading.section = { anchor: s[1], title: (s[2] || '').trim() };
      else heading.malformed = true;
    } else if (/^index$/i.test(text)) {
      heading.isIndex = true;
    }
    headings.push(heading);
  });
  const m = SECTION_FILE_RE.exec(name);
  // anchor: null for README.md, the anchor for a section file, undefined for anything else.
  const anchor = name === README ? null : m ? m[1] : undefined;
  return { name, lines, headings, fenced, indexOpen, indexClose, anchor };
}

// README.md first, then section files in anchor order, then anything else.
function orderFiles(files) {
  const rank = (f) => (f.anchor === null ? 0 : f.anchor === undefined ? 2 : 1);
  return [...files.values()].sort(
    (a, b) =>
      rank(a) - rank(b) ||
      (rank(a) === 1 ? compareAnchors(a.anchor, b.anchor) : a.name.localeCompare(b.name)),
  );
}

// files: Map of file name to lines.
function buildModel(files) {
  const scanned = new Map();
  for (const [name, lines] of files) scanned.set(name, scanFile(name, lines));
  const sections = new Map();
  const duplicates = [];
  for (const f of orderFiles(scanned)) {
    for (const h of f.headings) {
      if (!h.section) continue;
      const { anchor, title } = h.section;
      const s = { anchor, title, file: f.name, i: h.i, level: h.level, removed: /^\(removed\b/i.test(title) };
      if (sections.has(anchor)) duplicates.push({ first: sections.get(anchor), again: s });
      else sections.set(anchor, s);
    }
  }
  const readme = scanned.get(README);
  const first = readme && readme.headings[0];
  const h1 = first && first.level === 1 ? first : null;
  return { files: scanned, sections, duplicates, h1 };
}

const hasOwnFile = (s) => s.file === ownFile(s.anchor);
const sortedSections = (m) => [...m.sections.values()].sort(byAnchor);

// The first paragraph under the title.
function abstractOf(readme) {
  const h1 = readme.headings[0];
  if (!h1 || h1.level !== 1) return null;
  const { lines } = readme;
  let i = h1.i + 1;
  while (i < lines.length && isBlank(lines[i])) i++;
  const start = i;
  const body = [];
  for (; i < lines.length && !isBlank(lines[i]) && !HEADING_RE.test(lines[i]) && !RULE_RE.test(lines[i]); i++) {
    body.push(lines[i].trim());
  }
  if (!body.length || /^(>|[-*+][ \t]|\d+[.)][ \t]|\||<!--|```|~~~)/.test(body[0])) return null;
  return { i: start, text: body.join(' ') };
}

// Where a section's text ends in its file: at the next heading outside it, or at the index.
function rangeEnd(f, s) {
  let end = f.lines.length;
  if (f.indexOpen > s.i) end = f.indexOpen;
  for (const h of f.headings) {
    if (h.i <= s.i || h.i >= end) continue;
    if ((h.isIndex && f.name === README) || h.malformed || (h.section && !isWithin(h.section.anchor, s.anchor))) {
      return h.i;
    }
  }
  return end;
}

// ---------------------------------------------------------------- generated lines

const escapeLabel = (s) => s.replace(/[[\]]/g, '\\$&');

// Every section, nested by depth. An entry links the file that holds the section; one with no
// link is in README.md itself.
function renderIndex(m) {
  return sortedSections(m).map((s) => {
    const label = `§${s.anchor} ${s.title}`.trim();
    const entry = s.file === README ? label : `[${escapeLabel(label)}](${s.file})`;
    return `${'  '.repeat(depthOf(s.anchor) - 1)}- ${entry}`;
  });
}

// The first line of a section file: the SDD, then each ancestor section, each linking its file.
// The SDD is named by the README's title when that is well-formed, else by its id alone, so the
// crumb always opens with the id — which is how a crumb is told from text above the heading.
function renderBreadcrumb(m, anchor, id) {
  const title = m.h1 && TITLE_RE.test(m.h1.text) ? m.h1.text : id;
  const chain = [`[${escapeLabel(title)}](${README})`];
  const ancestors = [];
  for (let p = parentOf(anchor); p; p = parentOf(p)) ancestors.unshift(p);
  for (const a of ancestors) {
    const s = m.sections.get(a);
    chain.push(`[${escapeLabel(`§${a} ${s ? s.title : ''}`.trim())}](${ownFile(a)})`);
  }
  return `> ${chain.join(' › ')}`;
}

function currentIndex(readme) {
  if (readme.indexOpen < 0 || readme.indexClose < readme.indexOpen) return null;
  return readme.lines.slice(readme.indexOpen + 1, readme.indexClose);
}

// ---------------------------------------------------------------- checks

// Issues for one SDD folder. `fixable` ones are what fix repairs; a `structural` one stops fix
// from touching the doc at all, because moving text around it could lose or misplace some.
function checkDoc(m, { id, maxLines }) {
  const issues = [];
  const add = (file, i, message, kind = {}) =>
    issues.push({
      file,
      line: i === undefined || i < 0 ? undefined : i + 1,
      level: kind.warning ? 'warning' : 'error',
      message,
      fixable: Boolean(kind.fixable),
      structural: Boolean(kind.structural),
    });

  const readme = m.files.get(README);
  if (!readme) {
    add(README, undefined, 'missing: every SDD folder has a README.md entry file', { structural: true });
  } else {
    const t = m.h1 && TITLE_RE.exec(m.h1.text);
    if (!m.h1) add(README, 0, `must open with the title heading "# ${id} — <title>"`);
    else if (!t) add(README, m.h1.i, `the title heading must read "# ${id} — <title>"`);
    else if (t[1] !== id) add(README, m.h1.i, `the title says ${t[1]}, but the folder is ${id}`);

    const abs = abstractOf(readme);
    if (!abs) {
      add(README, m.h1 ? m.h1.i + 1 : 0, 'no abstract: open with one paragraph, under the title, saying what this SDD covers');
    } else if (abs.text.length > ABSTRACT_MAX) {
      add(README, abs.i, `the abstract is ${abs.text.length} characters; the limit is ${ABSTRACT_MAX}`);
    }

    if (readme.indexOpen >= 0 && readme.indexClose < 0) {
      add(README, readme.indexOpen, `the index has no closing ${INDEX_CLOSE}`, { structural: true });
    } else {
      const cur = currentIndex(readme);
      if (!cur) add(README, undefined, 'no generated index', { fixable: true });
      else if (!sameLines(cur, renderIndex(m))) add(README, readme.indexOpen, 'the index is out of date', { fixable: true });
    }
  }

  for (const f of orderFiles(m.files)) {
    let enclosing = null;
    for (const h of f.headings) {
      if (h.level === 1 && h !== m.h1) add(f.name, h.i, 'only README.md opens with a level-1 heading, and only once');
      if (h.malformed) {
        add(f.name, h.i, `malformed section heading "${h.text}": write "§<number> <title>", like "§3.2 Retries"`, {
          structural: true,
        });
      } else if (h.section) {
        const { anchor, title } = h.section;
        enclosing = anchor;
        if (!title) add(f.name, h.i, `§${anchor} has no title`);
        const want = levelFor(anchor);
        if (h.level !== want) {
          add(f.name, h.i, `§${anchor} is a level-${h.level} heading; its depth takes ${'#'.repeat(want)}`, { fixable: true });
        }
      } else if (h.isIndex && f.name === README) {
        enclosing = null;
      } else if (enclosing && h.level > 1 && h.level <= levelFor(enclosing)) {
        add(
          f.name,
          h.i,
          `the heading "${h.text}" sits at section level inside §${enclosing}: number it, or make it deeper than ${'#'.repeat(levelFor(enclosing))}`,
          { structural: true },
        );
      }
    }
  }

  for (const { first, again } of m.duplicates) {
    add(again.file, again.i, `§${again.anchor} is defined twice; the other is ${first.file}:${first.i + 1}`, { structural: true });
  }

  for (const s of sortedSections(m)) {
    const p = parentOf(s.anchor);
    const parent = p && m.sections.get(p);
    if (p && !parent) {
      add(s.file, s.i, `§${s.anchor} has no parent: there is no §${p}`, { structural: true });
    } else if (hasOwnFile(s)) {
      if (parent && !hasOwnFile(parent)) {
        add(s.file, s.i, `§${s.anchor} has its own file, but its parent §${p} does not; put §${s.anchor} back into ${parent.file}`, {
          structural: true,
        });
      }
    } else {
      const home = parent ? parent.file : README;
      if (s.file !== home) add(s.file, s.i, `§${s.anchor} belongs in ${home}, with its parent`, { structural: true });
    }
  }

  // A section file opens with its breadcrumb, then its own heading. Nothing else goes above.
  for (const f of orderFiles(m.files)) {
    if (f.anchor === null) continue;
    if (f.anchor === undefined) {
      add(f.name, undefined, 'not a section file: a file here is README.md or is named for the section it holds, like 3.2.md');
      continue;
    }
    const first = f.headings.find((h) => h.section || h.malformed);
    if (!first || !first.section || first.section.anchor !== f.anchor) {
      add(f.name, first ? first.i : undefined, `must open with the heading of §${f.anchor}`, { structural: true });
      continue;
    }
    for (let i = 0; i < first.i; i++) {
      if (isBlank(f.lines[i]) || (i === 0 && BREADCRUMB_RE.test(f.lines[i]))) continue;
      add(f.name, i, `text above the §${f.anchor} heading; only the breadcrumb goes there`, { structural: true });
      break;
    }
    const crumb = renderBreadcrumb(m, f.anchor, id);
    if (f.lines[0] !== crumb) {
      add(f.name, 0, BREADCRUMB_RE.test(f.lines[0] || '') ? 'the breadcrumb is out of date' : 'no breadcrumb', { fixable: true });
    }
  }

  // Siblings move out together: once one has its own file, all of them do.
  for (const kids of siblingGroups(m).values()) {
    const moved = kids.find(hasOwnFile);
    if (!moved) continue;
    for (const s of kids) {
      if (!hasOwnFile(s)) add(s.file, s.i, `§${s.anchor} needs its own file, like its sibling §${moved.anchor}`, { fixable: true });
    }
  }

  for (const f of orderFiles(m.files)) {
    if (f.lines.length <= maxLines || f.anchor === undefined) continue;
    const owner = f.anchor;
    const inline = inlineChildren(m, f.name, owner);
    const what = `${f.lines.length} lines, over the ${maxLines}-line limit`;
    if (inline.length) {
      add(f.name, undefined, `${what}; fix moves its ${inline.length} ${owner ? 'subsections' : 'sections'} into their own files`, {
        fixable: true,
      });
    } else if (owner) {
      add(f.name, undefined, `${what}, and §${owner} has no subsections to move out: divide it into nested sections (§${owner}.1, §${owner}.2, …), then run fix`);
    } else {
      add(f.name, undefined, `${what}, and has no sections left to move out: shorten the text above the index`);
    }
  }

  return issues;
}

function siblingGroups(m) {
  const groups = new Map();
  for (const s of sortedSections(m)) {
    const p = parentOf(s.anchor) ?? '';
    if (!groups.has(p)) groups.set(p, []);
    groups.get(p).push(s);
  }
  return groups;
}

// The direct subsections still inside a file. owner is null for README.md, whose children are
// the top-level sections.
function inlineChildren(m, fileName, owner) {
  return sortedSections(m).filter((s) => s.file === fileName && s.anchor !== owner && parentOf(s.anchor) === owner);
}

// ---------------------------------------------------------------- fix

// The next section to move into its own file: a sibling of one already moved, or else the first
// subsection of a file over the limit — whose siblings then follow by the first rule.
function nextMove(m, maxLines) {
  for (const kids of siblingGroups(m).values()) {
    if (!kids.some(hasOwnFile)) continue;
    const s = kids.find((k) => !hasOwnFile(k));
    if (s) return s.anchor;
  }
  for (const f of orderFiles(m.files)) {
    if (f.lines.length <= maxLines || f.anchor === undefined) continue;
    const [kid] = inlineChildren(m, f.name, f.anchor);
    if (kid) return kid.anchor;
  }
  return null;
}

// Cuts one section, with its subsections, out of its file into <anchor>.md.
function moveOut(files, m, anchor, id) {
  const s = m.sections.get(anchor);
  const f = m.files.get(s.file);
  const name = ownFile(anchor);
  if (files.has(name)) throw new Error(`${name} already exists`);
  const end = rangeEnd(f, s);
  const lines = files.get(s.file);
  files.set(s.file, trimEnd([...lines.slice(0, s.i), ...lines.slice(end)]));
  files.set(name, [renderBreadcrumb(m, anchor, id), '', ...trimEnd(lines.slice(s.i, end))]);
}

function applyBreadcrumbs(files, m, id) {
  for (const f of m.files.values()) {
    if (!f.anchor) continue;
    const crumb = renderBreadcrumb(m, f.anchor, id);
    const lines = files.get(f.name);
    if (lines[0] === crumb) continue;
    if (BREADCRUMB_RE.test(lines[0] || '')) lines[0] = crumb;
    else if (lines[0] === '') lines.unshift(crumb);
    else lines.unshift(crumb, '');
  }
}

function applyIndex(files, m) {
  const r = m.files.get(README);
  const lines = files.get(README);
  const block = [INDEX_OPEN, ...renderIndex(m), INDEX_CLOSE];
  if (r.indexOpen >= 0) {
    files.set(README, [...lines.slice(0, r.indexOpen), ...block, ...lines.slice(r.indexClose + 1)]);
    return;
  }
  const heading = r.headings.find((h) => h.isIndex);
  if (heading) {
    // An index written by hand: its list items give way to the generated block. Anything else
    // under the heading — a thematic break that closed it, a paragraph — is text, and follows the
    // block, one blank line between paragraphs.
    const after = r.headings.find((h) => h.i > heading.i);
    const end = after ? after.i : lines.length;
    const rest = [];
    for (let i = heading.i + 1; i < end; i++) {
      const line = lines[i];
      if (!r.fenced[i] && LIST_ITEM_RE.test(line)) continue;
      if (!r.fenced[i] && isBlank(line) && (!rest.length || isBlank(rest[rest.length - 1]))) continue;
      rest.push(line);
    }
    while (rest.length && isBlank(rest[rest.length - 1])) rest.pop();
    const body = ['', ...block];
    if (rest.length) body.push('', ...rest);
    if (end < lines.length) body.push('');
    files.set(README, [...lines.slice(0, heading.i + 1), ...body, ...lines.slice(end)]);
    return;
  }
  const first = r.headings.find((h) => h.section);
  if (first) files.set(README, [...lines.slice(0, first.i), '## Index', '', ...block, '', ...lines.slice(first.i)]);
  else files.set(README, [...trimEnd(lines), '', '## Index', '', ...block]);
}

// Everything fix repairs, in one pass: heading levels, then moves, with the breadcrumbs and the
// index regenerated before every size check, since both count towards a file's lines.
// Returns the new files and what changed, or the structural issues that stopped it.
function fixDoc(input, ctx) {
  const files = new Map([...input].map(([name, lines]) => [name, [...lines]]));
  let m = buildModel(files);
  const blocked = checkDoc(m, ctx).filter((x) => x.structural);
  if (blocked.length) return { files: input, actions: [], blocked };

  const actions = [];
  let levels = 0;
  for (const f of m.files.values()) {
    for (const h of f.headings) {
      if (!h.section || h.level === levelFor(h.section.anchor)) continue;
      files.get(f.name)[h.i] = `${'#'.repeat(levelFor(h.section.anchor))} ${h.text}`;
      levels++;
    }
  }
  if (levels) actions.push(`set ${levels} heading level${levels === 1 ? '' : 's'} from section depth`);

  const moves = new Map();
  for (;;) {
    m = buildModel(files);
    applyBreadcrumbs(files, m, ctx.id);
    applyIndex(files, buildModel(files));
    m = buildModel(files);
    const next = nextMove(m, ctx.maxLines);
    if (!next) break;
    const from = m.sections.get(next).file;
    if (!moves.has(from)) moves.set(from, []);
    moves.get(from).push(next);
    moveOut(files, m, next, ctx.id);
  }
  for (const [from, anchors] of moves) {
    actions.push(`moved ${anchors.map((a) => `§${a}`).join(', ')} out of ${from} into their own files`);
  }

  const crumbs = [...input.keys()].filter(
    (name) => SECTION_FILE_RE.test(name) && files.has(name) && files.get(name)[0] !== input.get(name)[0],
  ).length;
  if (crumbs) actions.push(`updated ${crumbs} breadcrumb${crumbs === 1 ? '' : 's'}`);
  const before = input.has(README) ? currentIndex(scanFile(README, input.get(README))) : null;
  const after = currentIndex(m.files.get(README));
  if (!before || !sameLines(before, after)) actions.push('regenerated the index');

  return { files, actions, blocked: null };
}

// ---------------------------------------------------------------- references

// A link target's path segments, without its fragment or query.
const targetParts = (target) => target.split('#')[0].split('?')[0].split('/');

// The SDD a link target points into — a file (SDD006-order-workflow.md), or a folder, whether
// the link ends on it (../sdd/SDD006-order-workflow) or goes into it (SDD006-order-workflow/3.md):
// its number, or null.
function linkedDoc(target) {
  const m = targetParts(target)
    .map((p) => FLAT_FILE_RE.exec(p) || DOC_DIR_RE.exec(p))
    .find(Boolean);
  return m ? Number(m[1]) : null;
}

// The SDD references on one line. kind: full (SDD011§3.2 or SDD011), noncanonical (SDD11),
// short (the §12 of SDD006§2.4.1/§12), prose (§8.1.2 of SDD006), link (a markdown link to an SDD
// file, looked for only when `markdown`), or bare (§3.2 alone, looked for only when `bare`).
function findRefs(line, { bare = false, markdown = false } = {}) {
  const refs = [];
  const taken = new Set();
  const spans = [];
  if (markdown) {
    for (const m of line.matchAll(LINK_RE)) {
      const num = linkedDoc(m[2]);
      if (num === null) continue;
      const anchor = m[3] ? m[3].slice(1) : null;
      refs.push({ col: m.index, kind: 'link', num, anchor, text: m[0] });
      spans.push([m.index, m.index + m[0].length]);
      if (anchor) taken.add(m.index + m[0].length - m[3].length);
    }
  }
  for (const m of line.matchAll(PROSE_RE)) {
    refs.push({ col: m.index, kind: 'prose', num: Number(m[2]), anchor: m[1], text: m[0] });
    taken.add(m.index);
  }
  for (const m of line.matchAll(REF_RE)) {
    if (spans.some(([a, b]) => m.index >= a && m.index < b)) continue;
    if (refs.some((r) => r.kind === 'prose' && m.index > r.col && m.index < r.col + r.text.length)) continue;
    const digits = m[1];
    const num = Number(digits);
    const kind = docId(num) === `SDD${digits}` ? 'full' : 'noncanonical';
    refs.push({ col: m.index, kind, num, anchor: m[2] || null, text: m[0] });
    if (!m[2]) continue;
    taken.add(m.index + 3 + digits.length);
    for (let p = m.index + m[0].length; ; ) {
      const t = TAIL_RE.exec(line.slice(p));
      if (!t) break;
      const at = p + t[1].length;
      taken.add(at);
      refs.push({ col: at, kind: 'short', num, anchor: t[2], text: `§${t[2]}`, head: m[0] });
      p += t[0].length;
    }
  }
  if (bare) {
    for (const m of line.matchAll(BARE_RE)) {
      if (!taken.has(m.index)) refs.push({ col: m.index, kind: 'bare', num: null, anchor: m[1], text: m[0] });
    }
  }
  return refs.sort((a, b) => a.col - b.col);
}

// Every reference in a file, with its line index. In markdown, fenced code is skipped; in an
// SDD's own files, so are the lines that define anchors rather than cite them — headings, the
// index, the breadcrumb — and a bare §3.2 counts as a reference to that SDD.
function refsInFile(name, lines, { markdown, inDoc }) {
  const scan = markdown ? scanFile(name, lines) : null;
  const skip = new Set();
  if (scan) {
    scan.fenced.forEach((f, i) => f && skip.add(i));
    if (inDoc) {
      for (const h of scan.headings) if (h.section || h.malformed) skip.add(h.i);
      if (scan.indexOpen >= 0) for (let i = scan.indexOpen; i <= Math.max(scan.indexClose, scan.indexOpen); i++) skip.add(i);
      if (BREADCRUMB_RE.test(lines[0] || '')) skip.add(0);
    }
  }
  const out = [];
  lines.forEach((line, i) => {
    if (skip.has(i) || (!line.includes('SDD') && !(inDoc && line.includes('§')))) return;
    for (const ref of findRefs(line, { bare: Boolean(inDoc), markdown })) out.push({ i, ...ref });
  });
  return out;
}

// What is wrong with one reference, if anything. docsByNum maps a number to its SDDs (more than
// one is a numbering clash, reported elsewhere); ownDoc is the SDD whose file holds the reference.
function validateRef(ref, docsByNum, ownDoc) {
  const err = (message) => ({ level: 'error', message });
  if (ref.kind === 'noncanonical') return err(`write ${docId(ref.num)}, not ${ref.text.replace(/§.*/, '')}`);
  const doc = ref.kind === 'bare' ? ownDoc : (docsByNum.get(ref.num) || [])[0];
  const id = ref.kind === 'bare' ? ownDoc.id : docId(ref.num);
  const full = `${id}${ref.anchor ? `§${ref.anchor}` : ''}`;
  if (ref.kind === 'short') return err(`short form: write ${full}, not §${ref.anchor} after ${ref.head}`);
  if (ref.kind === 'prose') return err(`write ${full}, not "${ref.text}"`);
  if (ref.kind === 'link') return err(`a link by file path breaks when the file moves: write ${full}`);
  if (!doc) return err(`${id} does not exist`);
  if (!ref.anchor) return null;
  const s = doc.model.sections.get(ref.anchor);
  if (!s) return err(ref.kind === 'bare' ? `no §${ref.anchor} in ${id}` : `${id} has no §${ref.anchor}`);
  if (s.removed) return { level: 'warning', message: `${id}§${ref.anchor} was removed: ${s.title}` };
  return null;
}

// Migration: every reference in the full form. SDD006§2.4.1/§12 becomes
// SDD006§2.4.1/SDD006§12, and "§8.1.2 of SDD006" becomes SDD006§8.1.2.
function expandRefs(line) {
  let count = 0;
  const short = line.replace(SHORT_FORM_RE, (whole, id, anchor, tail) => {
    const expanded = tail.replace(TAIL_ANCHOR_RE, (_, a) => {
      count++;
      return `${id}§${a}`;
    });
    return `${id}§${anchor}${expanded}`;
  });
  const out = short.replace(PROSE_RE, (whole, anchor, digits) => {
    count++;
    return `SDD${digits}§${anchor}`;
  });
  return { line: out, count };
}

// Migration: a markdown link to a single-file SDD becomes its plain id, since the file moves and
// an id never does. [SDD006](SDD006-order-workflow.md)§3.1 becomes SDD006§3.1, and
// [order workflow](SDD006-order-workflow.md) becomes "order workflow (SDD006)".
function rewriteDocLinks(line, idForFile) {
  let count = 0;
  const out = line.replace(LINK_RE, (whole, text, target, anchor = '') => {
    const id = idForFile(targetParts(target).pop());
    if (!id) return whole;
    count++;
    const label = text.trim();
    if (!label || label === id) return `${id}${anchor}`;
    if (!anchor && label.includes(id)) return label;
    return `${label} (${id}${anchor})`;
  });
  return { line: out, count };
}

module.exports = {
  README,
  ABSTRACT_MAX,
  DOC_DIR_RE,
  FLAT_FILE_RE,
  INDEX_OPEN,
  INDEX_CLOSE,
  docId,
  parentOf,
  compareAnchors,
  levelFor,
  splitLines,
  joinLines,
  scanFile,
  buildModel,
  abstractOf,
  renderIndex,
  renderBreadcrumb,
  checkDoc,
  fixDoc,
  findRefs,
  refsInFile,
  validateRef,
  expandRefs,
  rewriteDocLinks,
};
